### ISSUE TITLE
Support for building Arch Linux ARM packages in docker

### ISSUE THREAD

**Issue by ghost** [zocker-160/aur-builder#2]
Is it possible to build ARM packages using this builder?
Thanks

**Comment by zocker-160** [comment]
currently not, because the builder relies on the Archlinux Docker image, which currently only supports amd64

see under `Supported architectures`

https://hub.docker.com/_/archlinux

The Manjaro image does offer an arm build, so that should be possible, but I sadly don't have any ARM hardware that I could use for testing.

**Comment by ghost** [comment]
Okay, Thanks
